### ISSUE TITLE
Very Work 👍

### ISSUE THREAD

**Issue by JaceThings** [Discord-Theme-Addons/refined-user-connections#5]
No other conflicting theme is enabled, just removes the borders...
The previous issue on this repo seems to have occurred again.

![image](https://user-images.githubusercontent.com/60551230/131266236-b4bf6cfe-af12-45e2-8d33-2b4866820748.png)

**Comment by LuckFire** [comment]
which build is this occurring on? sorry for the late response, but i cannot seem to replicate.

please make sure you don't have any conflicting css that'd mess with this

**Comment by JaceThings** [comment]
This is on Discord Canary, with 0 themes and 0 custom CSS used, I have yet to test it on the stable build and PTB.

**Comment by LuckFire** [comment]
Interesting.. cause it works perfectly fine on canary for me. I'll look further into this.

**Comment by LuckFire** [comment]
I'm still unable to replicate without any other plugins and themes.. not to sure why it isn't working for you. Try redownloading maybe?

**Comment by JaceThings** [comment]
I actually did re-install it lmao, might have to reinstall canary maybe? Idk, guess it's a me problem

**Comment by LuckFire** [comment]
Can you send a screenshot of all the classes that appear for connected accounts?

**Comment by JaceThings** [comment]
idk what you mean by classes but this is what I think you meant:
![image](https://user-images.githubusercontent.com/60551230/142486285-272fbafd-60a5-4dba-b082-41ad4353e888.png)
![image](https://user-images.githubusercontent.com/60551230/142486535-23a2373b-af16-4c3a-a7e1-c4cffc30ce3b.png)

**Comment by LuckFire** [comment]
can you send the classes for inside connectedAccount-2JB-Z0

**Comment by JaceThings** [comment]
![image](https://user-images.githubusercontent.com/60551230/142491111-c3aa26a5-31b1-4b8d-90d0-2c8cf3de06f4.png)

**Comment by LuckFire** [comment]
yea im not too sure why it's not working, all of the classes are the same so weird
all i can suggest is make sure the theme is actually enabled or there isn't any conflicting themes or plugins.

maybe importing it will work so you could try that? put this at the top of your quick css
```css
@import url('https://discord-theme-addons.github.io/refined-user-connections/src/support/compiled.css');
```

**Comment by JaceThings** [comment]
the import function does nothing 💀 
but it's fine tho, as long as it technically works, guess its a me problem

**Comment by LuckFire** [comment]
sorry that i was unable to help, im legitimately so clueless as to why it doesnt work.
